version: '3'
services:

  api-general:
    build: ./apiGeneral
    ports:
      - "6969:8080"
    depends_on:
      - servicio-productos
      #- servicio-usuarios
      #- servicio-pedidos

  servicio-productos:
    build: ./ApiProducto

  # servicio-usuarios:
  #   build: ./MicroServicioUsuarios
  #   ports:
  #     - "8083:8083"

  # servicio-pedidos:
  #   build: ./pedidos-ktor
  #   ports:
  #     - "8080:8080"
