version: '3'
services:

  api-general:
    container_name: api-general
    build: ./apiGeneral
    ports:
      - "8080:8080"
    depends_on:
      - servicio-productos
      # - servicio-usuarios
      # - servicio-pedidos
    networks:
      - red
    
  servicio-productos:
    container_name: api-productos
    build: ./ApiProducto
    networks:
      - red

  mariaDb:
    container_name: mariaDb
    extends:
      file: ./ApiProducto/docker/docker-compose.yml
      service: mariaDb
    networks:
      - red


networks:
  red:
    driver: bridge
  # servicio-usuarios:
  #   build: ./MicroServicioUsuarios
  #   ports:
  #     - "8081:8081"

  # servicio-pedidos:
  #   build: ./pedidos-ktor
  #   ports:
  #     - "8083:8083"