version: '3.1'

services:
  mariaDb:
    container_name: mariaDb
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: admin
      MARIADB_PASSWORD: 1234
      MARIADB_DATABASE : tienda
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
