version: "3.5" # specify docker-compose version, v3.5 is compatible with docker 17.12.0+

# Define the services/containers to be run
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgresqlPassword
      POSTGRES_DB: tienda
      POSTGRES_USER: postgresqlUser
    volumes:
      - ./data/postgresql:/var/lib/postgresql
      - ./sql:/docker-entrypoint-initdb.d
