CREATE TABLE IF NOT EXISTS products(
    id BIGINT PRIMARY KEY,
    uuid UUID UNIQUE,
    name VARCHAR(255) NOT NULL,
    price DOUBLE NOT NULL,
    available BOOL NOT NULL,
    description VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    stock INTEGER NOT NULL,
    brand VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL
)